language: php

php:
  - '7.0'

cache:
    directories:
        - $HOME/.composer/cache

before_script:
  - composer install

script:
  - phpunit
  - php vendor/bin/php-cs-fixer --diff --dry-run -v fix